---
- name: get keystone admin password
  tags: [credentials]
  command: >-
    hiera -c /etc/puppet/hiera.yaml
    keystone::admin_password
  changed_when: false
  register: keystone_admin_password

- name: get keystone internal endpoint
  tags: [credentials]
  command: >-
    hiera -c /etc/puppet/hiera.yaml
    keystone::endpoint::internal_url
  changed_when: false
  register: keystone_endpoint_internal

- name: get keystone public endpoint
  tags: [credentials]
  command: >-
    hiera -c /etc/puppet/hiera.yaml
    keystone::endpoint::public_url
  changed_when: false
  register: keystone_endpoint_public

- name: get keystone region
  tags: [credentials]
  command: hiera -c /etc/puppet/hiera.yaml keystone::endpoint::region
  changed_when: false
  register: keystone_region
