---
- hosts: controller[0]
  become: true
  become_user: root
  run_once: true
  roles:
    - credentials/fetch

- hosts: undercloud:controller
  become: true
  become_user: root
  roles:
    - credentials/create
