- CountDefault: 1
  HostnameFormatDefault: '%stackname%-networker-%index%'
  ServicesDefault:
  - OS::Local::Services::PatchPuppetModules
  - OS::TripleO::Services::Aide
  - OS::TripleO::Services::AuditD
  - OS::TripleO::Services::CACerts
  - OS::TripleO::Services::CertmongerUser
  - OS::TripleO::Services::Collectd
  - OS::TripleO::Services::ContainersLogrotateCrond
  - OS::TripleO::Services::Docker
  - OS::TripleO::Services::Fluentd
  - OS::TripleO::Services::IpaClient
  - OS::TripleO::Services::Ipsec
  - OS::TripleO::Services::Kernel
  - OS::TripleO::Services::LoginDefs
  - OS::TripleO::Services::MetricsQdr
  - OS::TripleO::Services::MySQLClient
  - OS::TripleO::Services::NeutronCorePlugin
  - OS::TripleO::Services::NeutronDhcpAgent
  - OS::TripleO::Services::NeutronL2gwAgent
  - OS::TripleO::Services::NeutronL3Agent
  - OS::TripleO::Services::NeutronLbaasv2Agent
  - OS::TripleO::Services::NeutronML2FujitsuCfab
  - OS::TripleO::Services::NeutronML2FujitsuFossw
  - OS::TripleO::Services::NeutronMetadataAgent
  - OS::TripleO::Services::NeutronOvsAgent
  - OS::TripleO::Services::NeutronVppAgent
  - OS::TripleO::Services::Ntp
  - OS::TripleO::Services::OVNController
  - OS::TripleO::Services::OpenDaylightOvs
  - OS::TripleO::Services::Rhsm
  - OS::TripleO::Services::Securetty
  - OS::TripleO::Services::SensuClient
  - OS::TripleO::Services::SkydiveAgent
  - OS::TripleO::Services::Snmp
  - OS::TripleO::Services::Sshd
  - OS::TripleO::Services::Timezone
  - OS::TripleO::Services::TripleoFirewall
  - OS::TripleO::Services::TripleoPackages
  - OS::TripleO::Services::Tuned
  default_route_networks: []
  disable_constraints: true
  name: NetworkerDeployedServer
  networks:
  - InternalApi
  - Tenant
  tags: []

