###############################################################################
# Role: Undercloud                                                            #
###############################################################################
- name: Undercloud
  description: |
    EXPERIMENTAL. A role to deploy the  minimal undercloud for pre-provisioned
    deployed servers via heat using the 'openstack undercloud deploy' command.
    Should be used with the 'environments/docker-uc-light.yaml' template
    instead of the 'environments/docker.yaml'.
  CountDefault: 1
  disable_constraints: True
  tags:
    - primary
    - controller
  ServicesDefault:
    - OS::TripleO::Services::ContainersLogrotateCrond
    - OS::TripleO::Services::Docker
    - OS::TripleO::Services::DockerRegistry
    - OS::TripleO::Services::HeatApi
    - OS::TripleO::Services::HeatApiCfn
    - OS::TripleO::Services::HeatEngine
    - OS::TripleO::Services::Keystone
    - OS::TripleO::Services::LoginDefs
    - OS::TripleO::Services::Memcached
    - OS::TripleO::Services::MistralApi
    - OS::TripleO::Services::MistralEngine
    - OS::TripleO::Services::MistralExecutor
    - OS::TripleO::Services::MySQL
    - OS::TripleO::Services::NeutronApi
    - OS::TripleO::Services::NeutronCorePlugin
    - OS::TripleO::Services::NeutronDhcpAgent
    - OS::TripleO::Services::RabbitMQ
    - OS::TripleO::Services::Rhsm
    - OS::TripleO::Services::SwiftProxy
    - OS::TripleO::Services::SwiftRingBuilder
    - OS::TripleO::Services::SwiftStorage
    - OS::TripleO::Services::Zaqar
