---
- name: check if networks exist
  command: >-
    openstack
    network show {{ item.name }}
  failed_when: false
  changed_when: net_check.rc != 0
  register: net_check
  with_items: "{{ neutron_networks }}"

- name: create networks
  command: >-
    openstack
    network create {{ item.item.name }}
  when: item.rc != 0
  with_items: "{{ net_check.results }}"

- name: check if subnets exist
  command: >-
    openstack
    subnet show {{ item.name }}-subnet
  failed_when: false
  changed_when: subnet_check.rc != 0
  register: subnet_check
  with_items: "{{ neutron_networks }}"

- name: create subnets
  command: >-
    openstack
    subnet create {{ item.item.name }}-subnet
    --network {{ item.item.name }}
    --dns-nameserver {{ item.item.nameserver|default('8.8.8.8') }}
    --subnet-range {{ item.item.cidr }}
  when: item.rc != 0
  with_items: "{{ subnet_check.results }}"
