---
- name: check if routers exist
  command: >-
    openstack
    router show {{ item.name }}
  failed_when: false
  changed_when: router_check.rc != 0
  register: router_check
  with_items: "{{ neutron_routers }}"

- name: create routers
  command: >-
    openstack
    router create {{ item.item.name }}
  when: item.rc != 0
  with_items: "{{ router_check.results }}"

- name: set router gateway
  command: >-
    openstack
    router set --external-gateway {{ item.gateway }} {{ item.name }}
  when: item.gateway is defined
  with_items: "{{ neutron_routers }}"

- name: connect subnets
  command: >-
    openstack
    router add subnet
    {{ item.0.name }} {{ item.1.name }}
  with_subelements:
    - "{{ neutron_routers }}"
    - subnets
