images:
  horizon:
    from: DockerHorizonImage
    replace:
      - DockerHorizonImage
      - DockerHorizonConfigImage

  keystone:
    from: DockerKeystoneImage
    replace:
      - DockerKeystoneImage
      - DockerKeystoneConfigImage
