---
- name: set sahara interface facts
  set_fact:
    sahara_net_interface: "vlan{{ sahara_net_vlan_id }}"
    sahara_net_address: "{{ sahara_net_cidr|nthhost(10 + groups.controller.index(inventory_hostname)) }}"

- name: configure sahara network interface
  template:
    src: ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ sahara_net_interface }}"

- name: bring up interface
  tags: [ifcfg]
  command: "ifup {{ sahara_net_interface }}"
