---
- block:
    - name: create temporary directory for images
      tempfile:
        state: directory
        suffix: images
      register: tempdir

    - name: check if images exist
      command: >-
        openstack --os-cloud {{ cloud_name }}
        image show {{ item.name }}
      failed_when: false
      changed_when: image_check.rc != 0
      register: image_check
      with_items: "{{ glance_images }}"

    - name: download remote images
      get_url:
        url: "{{ item.item.url }}"
        dest: "{{ tempdir.path }}/{{ item.item.name }}.img"
      when: item.rc != 0
      with_items: "{{ image_check.results }}"

    - name: create images
      command: >-
        openstack --os-cloud {{ cloud_name }}
        image create {{ item.item.name }}
        --container-format {{ item.item.container_format|default('bare') }}
        --disk-format {{ item.item.format }}
        --file {{ tempdir.path }}/{{ item.item.name }}.img
        {% if not item.item.private|default('false') %}--public{% endif %}
      when: item.rc != 0
      with_items: "{{ image_check.results }}"
  always:
    - name: clean up temporary directory
      file:
        path: "{{ tempdir.path }}"
        state: absent
  tags: [images]
