---
- name: prepare all hosts
  hosts: undercloud:overcloud
  become: true
  tags: [all-prep]
  roles:
    - all-prep

- name: prepare undercloud
  hosts: undercloud
  become: true
  tags: [undercloud-prep]
  roles:
    - role: undercloud-prep

- name: prepare stack user on undercloud
  hosts: undercloud
  become: true
  become_user: stack
  roles:
    - stackuser

- name: prepare overcloud
  hosts: overcloud
  tags: [overcloud-prep]
  become: true
  roles:
    - mocrepo
    - overcloud-prep

- name: prepare compute hosts
  hosts: compute
  become: true
  tags: [compute-prep]
  roles:
    - openvswitch
    - zabbix
