---
- name: prepare all hosts
  hosts: undercloud:overcloud
  become: true
  roles:
    - all-prep

- name: prepare undercloud
  hosts: undercloud
  become: true
  roles:
    - undercloud-prep
    - selinux_relabel

- name: prepare stack user on undercloud
  hosts: undercloud
  become: true
  become_user: stack
  roles:
    - stackuser
    - foremancli

- name: prepare overcloud
  hosts: overcloud
  tags: [bugs, openvswitch]
  become: true
  roles:
    - overcloud-prep
    - bug/1642588-openvswitch-start
    - bug/1642591-openvswitch-selinux
    - selinux_relabel

- name: prepare compute hosts
  hosts: compute
  tags: [bugs, libvirt]
  become: true
  roles:
    - bug/1647828-libvirt-guests

- name: prepare sahara network on controllers
  hosts: controller
  tags: [sahara]
  become: true
  roles:
    - sahara_network/controller

- name: prepare sahara network on networkers
  hosts: network
  tags: [sahara]
  become: true
  roles:
    - sahara_network/networker
