---
- name: prepare all hosts
  hosts: undercloud:overcloud
  become: true
  roles:
    - all-prep

- name: prepare undercloud
  hosts: undercloud
  become: true
  roles:
    - role: undercloud-prep
      tags: [undercloud-prep]
    - selinux_relabel

- name: prepare stack user on undercloud
  hosts: undercloud
  become: true
  become_user: stack
  roles:
    - stackuser
    - foremancli
