heat_template_version: pike

description: >
  OpenStack Keystone federation with mod_auth_openidc

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

  KeystoneFederationMethods:
    type: string
    default: password,token,openidc,saml2
  KeystoneFederationIdpName:
    type: string
  KeystoneFederationProviderMetadataUrl:
    type: string
  KeystoneFederationClientId:
    type: string
  KeystoneFederationClientSecret:
    type: string

outputs:
  role_data:
    description: Role data for the Keystone role.
    value:
      service_name: keystone-federation
      config_settings:
        keystone::federation::openidc::methods:
          {get_param: KeystoneFederationMethods}
        keystone::federation::openidc::idp_name:
          {get_param: KeystoneFederationIdpName}
        keystone::federation::openidc::openidc_provider_metadata_url:
          {get_param: KeystoneFederationProviderMetadataUrl}
        keystone::federation::openidc::openidc_client_id:
          {get_param: KeystoneFederationClientId}
        keystone::federation::openidc::openidc_client_secret:
          {get_param: KeystoneFederationClientSecret}
      step_config: |
        include ::keystone::federation::openidc
