---
- name: check if volume types exist
  tags: [cinder]
  command: >-
    openstack --os-cloud {{ cloud_name }} volume type show {{ item.name }}
  with_items: "{{ cinder_volume_types }}"
  ignore_errors: true
  register: volume_type_check

- name: create volume_types
  tags: [cinder]
  command: >-
    openstack --os-cloud {{ cloud_name }}
    volume type create {{ item.item.name }}
    --property volume_backend_name={{ item.item.volume_backend_name }}
  when: item is failed
  with_items: "{{ volume_type_check.results }}"
