---
- hosts: localhost
  tags: [network]
  vars:
    number_of_networks: 2
  tasks:
    - include_role:
        name: network
      vars:
        index: "{{ item }}"
      with_sequence: start=0 end={{ number_of_networks - 1 }}

    - name: open up default security group
      os_security_group_rule:
        security_group: default
        protocol: "{{ item.protocol }}"
      with_items:
        - protocol: tcp
        - protocol: udp
        - protocol: icmp
