---
- hosts: localhost
  tags: [network]
  tasks:
    - name: create network
      os_network:
        name: net0

    - name: create subnet
      os_subnet:
        name: net0-subnet0
        network_name: net0
        cidr: 172.16.254.0/24
        dns_nameservers:
          - 8.8.8.8
          - 8.8.4.4

    - name: create router
      os_router:
        name: extrouter
        network: external
        interfaces:
          - net0-subnet0

    - name: open up default security group
      os_security_group_rule:
        security_group: default
        protocol: "{{ item.protocol }}"
      loop:
        - protocol: tcp
        - protocol: udp
        - protocol: icmp
