---
clouds:
  {{ cloud_basename }}-admin:
    auth:
      username: admin
      project_name: admin
      password: "{{ credentials.keystone_admin_password.stdout }}"
      auth_url: "{{ credentials['keystone_endpoint_' + keystone_endpoint].stdout }}"
      user_domain_name: Default
      project_domain_name: Default
    region: "{{ credentials.keystone_region.stdout }}"
    identity_api_version: 3
    interface: public
