---
- hosts: overcloud
  gather_facts: false
  roles:
    - ansible-modules-bitwarden
  tasks:
    - raw: racadm getsysinfo
      delegate_to: "{{ ipmi_host }}"
      register: sysinfo

    - name: create sysinfo directory
      run_once: true
      delegate_to: localhost
      file:
        path: ./sysinfo
        state: directory

    - name: write sysinfo to local file
      delegate_to: localhost
      copy:
        content: "{{ sysinfo.stdout }}"
        dest: "./sysinfo/{{ inventory_hostname }}.txt"
