---
- name: create projects
  tags: [keystone]
  command: >-
    openstack --os-cloud {{ cloud_name }}  project create
    --or-show
    {{ item.name }}
  with_items: "{{ keystone_projects }}"

- name: create users
  tags: [keystone]
  command: >-
    openstack --os-cloud {{ cloud_name }}  user create
    --or-show
    {{ item.name }}
    --email {{ item.email }}
    --password {{ item.password }}
  with_items: "{{ keystone_users }}"

# we have an explicit "set password" step to account for situations
# where the user may already exist but the password has changed.
- name: set user passwords
  tags: [keystone]
  command: >-
    openstack --os-cloud {{ cloud_name }}  user set
    {{ item.name }} --password {{ item.password }}
  with_items: "{{ keystone_users }}"

- name: assign roles
  tags: [keystone]
  command: >-
    openstack --os-cloud {{ cloud_name }} role add
    --project {{ item.project }}
    --user {{ item.name }}
    _member_
  with_items: "{{ keystone_users }}"
