---
undercloud_packages:
  - python-tripleoclient
  - git
  - rubygem-hammer_cli_foreman
  - ceph-ansible

undercloud_authorized_keys:
  - key: https://github.com/larsks.keys
    comment: lars@redhat.com

foreman_url: https://kzn-foreman.kzn.moc/
foreman_admin_user: admin
foreman_admin_pass: "{{ foreman_admin_password }}"
