---
heat_template_version: pike

parameters:
  servers:
    type: json
  FloatingNetworkVlanId:
    type: string

resources:
  FinishNetworkConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
        - name: floating_network_vlan_id
      config: |
        - hosts: localhost
          connection: local
          tasks:
            - set_fact:
                floating_network_vlan_interface: "vlan{{floating_network_vlan_id}}"

            - copy:
                mode: "0755"
                dest: "/sbin/ifup-local"
                content: |
                  #!/bin/sh
                  DEVICE=$1

                  if [ "$DEVICE" = "{{ floating_network_vlan_interface }}" ]; then

                    # if the target interface does not exist, exit
                    # with no changes
                    if ! ip addr show $DEVICE; then
                      exit 0
                    fi

                    # if br-ex does not exist, exit with no changes
                    if ! ovs-vsctl list-ports br-ex; then
                      exit 0
                    fi

                    # if the interface has already been added to the bridge,
                    # exit with no changes
                    if ovs-vsctl list-ports br-ex | grep -q $DEVICE; then
                      exit 0
                    fi

                    # add the target interface to the bridge
                    ovs-vsctl add-port br-ex $DEVICE

                  fi

            - command: "/sbin/ifup-local {{ floating_network_vlan_interface }}"

  FinishNetworkDeployments:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      name: FinishNetworkDeployments
      servers: {get_param: servers}
      config: {get_resource: FinishNetworkConfig}
      actions: ['CREATE', 'UPDATE']
      input_values:
        floating_network_vlan_id: {get_param: FloatingNetworkVlanId}
