---
- name: check if flavors exist
  tags: [nova]
  command: >-
    openstack --os-cloud {{ cloud_name }}  flavor show {{ item.name }}
  with_items: "{{ nova_flavors }}"
  ignore_errors: true
  register: flavor_check

- name: create flavors
  tags: [nova]
  command: >-
    openstack --os-cloud {{ cloud_name }}  flavor create {{ item.item.name }}
    --ram {{ item.item.ram }}
    --vcpus {{ item.item.vcpus }}
    --disk {{ item.item.disk }}
  when: item is failed
  with_items: "{{ flavor_check.results }}"

- name: set flavor properties
  tags: [nova]
  command: >-
    openstack --os-cloud {{ cloud_name }}  flavor set
    {%for prop in item.properties.items()%}--property
    {{prop.0}}={{prop.1}} {%endfor %} {{ item.name }}
  with_items: "{{ nova_flavors }}"
