---
- name: create flavors
  tags: [flavors]
  os_nova_flavor:
    state: present
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
    extra_specs: "{{ item.properties }}"
  when: only_flavor is not defined or item.name == only_flavor
  loop: "{{ nova_flavors }}"
