FROM {{ image_info.build_from_image }}

COPY rhel7local.repo /etc/yum.repos.d/rhel7local.repo
RUN yum -y install mod_auth_openidc patch

# https://bugs.launchpad.net/keystone/+bug/1738895
COPY 0001-Fix-list-users-by-name.patch /root/
RUN cd /usr/lib/python2.7/site-packages/keystone; \
	patch -p2 < /root/0001-Fix-list-users-by-name.patch
