---
- name: gather facts from overcloud hosts
  hosts: overcloud
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: force gather facts from overcloud hosts
      tags: [always]
      setup:
      when: not skip_facts|default(false)|bool

- name: generate files
  hosts: localhost
  tags: [templates]
  roles:
    - deploy-config
