---
- hosts: controller[0]
  become: true
  become_user: root
  run_once: true
  tasks:
    - include_role:
        name: overcloud_credentials
        tasks_from: fetch

- hosts: undercloud:controller
  become: true
  become_user: root
  tasks:
    - include_role:
        name: overcloud_credentials
        tasks_from: create
