---
- hosts: controller
  tags: [keystone]
  tasks:
    - name: patch keystone trusted_dashboard
      include_role:
        name: patch_keystone
        tasks_from: patch_trusted_dashboard.yml

- hosts: overcloud
  tags: [martians]
  tasks:
    - name: disable log_martians
      include_role:
        name: disable_log_martians
