- hosts: overcloud
  gather_facts: false
  tasks:
    - name: change power state
      delegate_to: ipmi-gw
      changed_when: false
      command: >
        ipmitool -I lanplus -H {{ ipmi_host }}
        -U {{ ipmi_user }} -P {{ ipmi_pass }}
        chassis power {{ power_state|default('on') }}
