---
- name: install virt guest shutdown units
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
  with_items:
    - containerized-libvirt-guests.service
    - virt-guest-shutdown.target

- name: install libvirt guests configuration
  template:
    src: libvirt-guests.sysconfig
    dest: /etc/sysconfig/libvirt-guests
    owner: root
    group: root
    mode: "0644"

- meta: flush_handlers

- name: activate virt guest shutdown units
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - containerized-libvirt-guests.service
    - virt-guest-shutdown.target
