---
- name: configure .bashrc
  blockinfile:
    path: "{{ stack_home }}/.bashrc"
    block: |
      if [ -f $HOME/stackrc ]; then
              . $HOME/stackrc
      fi

- name: clone director configuration
  git:
    repo: https://github.com/cci-moc/rhosp-director-config
    version: "{{ config_repo_version|default('master') }}"
    dest: "{{ stack_home }}/rhosp-director-config"
    recursive: true
